export const ENV_KEYS={
  
  POSTGRES_USERNAME:'POSTGRES_USERNAME',
  POSTGRES_PASSWORD:'POSTGRES_PASSWORD',
  POSTGRES_DATABASE:'POSTGRES_DATABASE',
  POSTGRES_HOST:'POSTGRES_HOST',
  POSTGRES_PORT:'POSTGRES_PORT',

  PORT:'PORT'
}